name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      
    - name: Compile project
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ps2dev/ps2dev:v1.0 sh -c "apk add build-base git zip && make CDSUPPORT=1 NOT_PACKED=1"
        
    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Get repository name
      id: repname
      run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e 's/:refs//')" >> $GITHUB_OUTPUT
        
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.repname.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}
        path: './**/*.elf'

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest development build"
        files: './**/*.elf'
